from __future__ import annotations

from pathlib import Path
from typing import Optional

import typer
from rich.markup import escape

from mysuite.utils import jsonout
from mysuite.utils.console import console, log_error, log_step

app = typer.Typer(help="A folder of test files generated by mysuite itself (CC0): try every tool without using your own pictures.", no_args_is_help=True)


@app.command("make", help="Generate the test folder (about 60 files, 10 MB, a few seconds). Nothing is downloaded.")
@jsonout.with_json("testcases")
def make(
    out: Path = typer.Option(Path("mysuite-testcases"), "--out", "-o", help="Folder to create."),
    overwrite: bool = typer.Option(False, "--overwrite/--no-overwrite", help="Write into a folder that already exists."),
) -> None:
    from mysuite.testcases.generate import generate

    if out.exists() and any(out.iterdir()) and not overwrite:
        log_error(f"{escape(str(out))} already has files - pick another --out or pass --overwrite")
        raise typer.Exit(1)
    from mysuite import sandbox

    sandbox.check_write(Path(out).resolve() / "MANIFEST.json")
    items, skipped = generate(out)
    for it in items:
        jsonout.add_item(output=Path(out) / it.path, description=it.description, exercises=it.exercises, status="written")
    for path, why in skipped:
        jsonout.add_warning(f"{path} not generated: {why}")
    jsonout.set_extra(folder=Path(out).resolve(), count=len(items), license="CC0-1.0", not_generated=[p for p, _ in skipped])
    log_step(f"{len(items)} files in {escape(str(out))}  [dim](see its README.md for what each one is for)[/dim]")
    for path, why in skipped:
        console.print(f"[dim]  skipped {escape(path)}: {escape(why)}[/dim]")


@app.command("list", help="List what the generator makes, and what each file exercises, without writing anything.")
@jsonout.with_json("testcases-list")
def list_files() -> None:
    import tempfile

    from mysuite.testcases.generate import generate

    with tempfile.TemporaryDirectory(prefix="mysuite-tc-") as d:
        items, skipped = generate(Path(d))
    for it in items:
        jsonout.add_item(path=it.path, description=it.description, exercises=it.exercises, needs=it.needs, status="ok")
        console.print(f"[bold]{escape(it.path)}[/bold]  [dim]{escape(it.description)}[/dim]")
